In [165]:
import pandas as pd 


In [166]:
df=pd.read_csv('loan_pred.csv')

In [167]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [168]:
df.keys()

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [169]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [170]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [171]:
df['Dependents']=df['Dependents'].fillna(df['Dependents'].mode()[0])

In [172]:
df['Self_Employed']=df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

In [173]:
df['LoanAmount']=df['LoanAmount'].fillna(df['LoanAmount'].mode()[0])

In [174]:
df['Loan_Amount_Term']=df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0])

In [175]:
df['Credit_History']=df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [176]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              3
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [177]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0       120.0             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [182]:
df.drop('Loan_ID',axis=1,inplace=True)

In [183]:
df

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0       120.0             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [193]:
from sklearn.preprocessing import LabelEncoder

In [194]:
lb=LabelEncoder()

In [195]:
df['Loan_Status']=lb.fit_transform(df['Loan_Status'])

In [197]:
z=['Gender','Married','Education','Self_Employed','Property_Area','Dependents','Loan_Status']
for num in z:
    df[num]=lb.fit_transform(df[num].astype(str))
df    

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0           0          0              0             5849   
1         1        1           1          0              0             4583   
2         1        1           0          0              1             3000   
3         1        1           0          1              0             2583   
4         1        0           0          0              0             6000   
..      ...      ...         ...        ...            ...              ...   
609       0        0           0          0              0             2900   
610       1        1           3          0              0             4106   
611       1        1           1          0              0             8072   
612       1        1           2          0              0             7583   
613       0        0           0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0       120.0             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  Loan_Status  
0                2            1  
1                0            0  
2                2            1  
3                2            1  
4                2            1  
..             ...          ...  
609              0            1  
610              0            1  
611              2            1  
612              2            1  
613              1            0  

[614 rows x 12 columns]

In [205]:
x=df.iloc[:,0:-1]

In [206]:
y=df.iloc[:,-1]

In [207]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

In [208]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()

In [209]:
x=st.fit_transform(x)

In [210]:
x

array([[ 0.47234264, -1.35784704, -0.73780632, ...,  0.2732313 ,
         0.41173269,  1.22329839],
       [ 0.47234264,  0.70581158,  0.25346957, ...,  0.2732313 ,
         0.41173269, -1.31851281],
       [ 0.47234264,  0.70581158, -0.73780632, ...,  0.2732313 ,
         0.41173269,  1.22329839],
       ...,
       [ 0.47234264,  0.70581158,  0.25346957, ...,  0.2732313 ,
         0.41173269,  1.22329839],
       [ 0.47234264,  0.70581158,  1.24474546, ...,  0.2732313 ,
         0.41173269,  1.22329839],
       [-2.11710719, -1.35784704, -0.73780632, ...,  0.2732313 ,
        -2.42876026, -0.04760721]])

In [211]:
xf=pd.DataFrame(data=x)
print(xf)

           0         1         2         3         4         5         6   \
0    0.472343 -1.357847 -0.737806 -0.528362 -0.392601  0.072991 -0.554487   
1    0.472343  0.705812  0.253470 -0.528362 -0.392601 -0.134412 -0.038732   
2    0.472343  0.705812 -0.737806 -0.528362  2.547117 -0.393747 -0.554487   
3    0.472343  0.705812 -0.737806  1.892641 -0.392601 -0.462062  0.251980   
4    0.472343 -1.357847 -0.737806 -0.528362 -0.392601  0.097728 -0.554487   
..        ...       ...       ...       ...       ...       ...       ...   
609 -2.117107 -1.357847 -0.737806 -0.528362 -0.392601 -0.410130 -0.554487   
610  0.472343  0.705812  2.236021 -0.528362 -0.392601 -0.212557 -0.554487   
611  0.472343  0.705812  0.253470 -0.528362 -0.392601  0.437174 -0.472404   
612  0.472343  0.705812  1.244745 -0.528362 -0.392601  0.357064 -0.554487   
613 -2.117107 -1.357847 -0.737806 -0.528362  2.547117 -0.134412 -0.554487   

           7         8         9         10  
0   -0.302759  0.273231  0.41

In [212]:
xf.to_csv('Loan_pred.cvs')

In [213]:
x.mean()

-1.6043495292184672e-17

In [214]:
x.std()

1.0

In [224]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [225]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=20,random_state=45)

In [226]:
train_x

array([[ 0.47234264,  0.70581158, -0.73780632, ...,  0.2732313 ,
         0.41173269,  1.22329839],
       [ 0.47234264,  0.70581158,  1.24474546, ...,  0.2732313 ,
         0.41173269, -1.31851281],
       [ 0.47234264,  0.70581158, -0.73780632, ...,  0.2732313 ,
         0.41173269,  1.22329839],
       ...,
       [ 0.47234264,  0.70581158,  1.24474546, ...,  0.2732313 ,
         0.41173269, -1.31851281],
       [-2.11710719,  0.70581158, -0.73780632, ...,  0.2732313 ,
         0.41173269, -0.04760721],
       [-2.11710719,  0.70581158, -0.73780632, ...,  0.2732313 ,
        -2.42876026, -0.04760721]])

In [227]:
test_x

array([[-2.11710719, -1.35784704, -0.73780632, -0.52836225, -0.39260074,
        -0.63948522,  0.06113628, -0.50486972,  0.2732313 , -2.42876026,
        -0.04760721],
       [ 0.47234264,  0.70581158,  0.25346957, -0.52836225, -0.39260074,
        -0.34214238, -0.55448733, -0.58809171,  0.2732313 ,  0.41173269,
        -0.04760721],
       [ 0.47234264,  0.70581158,  2.23602135, -0.52836225, -0.39260074,
        -0.3889964 , -0.55448733, -0.55242515,  0.2732313 ,  0.41173269,
         1.22329839],
       [ 0.47234264,  0.70581158,  0.25346957,  1.89264089, -0.39260074,
        -0.51841836,  0.30875378, -0.20764834,  0.2732313 ,  0.41173269,
         1.22329839],
       [ 0.47234264,  0.70581158, -0.73780632,  1.89264089, -0.39260074,
        -0.41422549,  0.04403563, -0.48109201,  0.2732313 ,  0.41173269,
        -0.04760721],
       [ 0.47234264, -1.35784704, -0.73780632, -0.52836225, -0.39260074,
         0.09772844, -0.55448733, -0.05309323,  0.2732313 ,  0.41173269,
         1.223

In [228]:
lg=LogisticRegression()

In [230]:
lg.fit(train_x,train_y)

LogisticRegression()

In [231]:
pred=lg.predict(test_x)
print(pred)

[0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1]


In [232]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [233]:
print('accuracy_score:',accuracy_score(test_y,pred))

accuracy_score: 0.85


In [234]:
print(confusion_matrix(test_y,pred))

[[ 4  3]
 [ 0 13]]


In [235]:
print(classification_report(test_y,pred))

              precision    recall  f1-score   support

           0       1.00      0.57      0.73         7
           1       0.81      1.00      0.90        13

    accuracy                           0.85        20
   macro avg       0.91      0.79      0.81        20
weighted avg       0.88      0.85      0.84        20



In [327]:
from sklearn.neighbors import KNeighborsClassifier


In [328]:
knn=KNeighborsClassifier()

In [329]:
knn.fit(train_x,train_y)

KNeighborsClassifier()

In [330]:
predknn=knn.predict(test_x)

In [331]:
predknn

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1])

In [332]:
print('accuracy_score:',accuracy_score(predknn,test_y))

accuracy_score: 0.9


In [380]:
x=np.array([1,1,2,1,0,450,40.0,200,90,1.0,1])

In [381]:
def predknn_function(x):
    x=x.reshape(1,-1)
    pred=knn.predict(x)
    if pred==0:
        print("loan agreed")
    elif pred==1:
        print("loan canceled")
    else:
        print('none')
    

In [382]:
predknn_function(x)

loan canceled
